#!/bin/sh -e

case "$1" in
    purge)
        rm -rf /usr/share/classifier

        # Remove classifier log files
        rm -rf /var/log/classifier
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)


        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

exit 0
