prefix = /usr/local
datadir = $(prefix)/share
confdir = /etc
initdir = $(confdir)/init.d
rubylibdir = $(shell ruby -rrbconfig -e "puts RbConfig::CONFIG['sitelibdir']")
rundir = /var/run

ifeq ($(wildcard /etc/redhat-release),/etc/redhat-release)
	defaultsdir = $(confdir)/sysconfig
	initsrc = ext/redhat/init
	rundir = /var/run/<%= EZBake::Config[:project] %>
else
	defaultsdir = $(confdir)/default
	initsrc = ext/debian/ezbake.init
endif

<%= EZBake::Config[:project] %>.jar:
	lein uberjar
	mv target/<%= EZBake::Config[:project] %>.jar <%= EZBake::Config[:project] %>.jar

install-<%= EZBake::Config[:project] %>: <%= EZBake::Config[:project] %>.jar
	install -d -m 0755 "$(DESTDIR)$(datadir)/<%= EZBake::Config[:project] %>"
	install -m 0644 <%= EZBake::Config[:project] %>.jar "$(DESTDIR)$(datadir)/<%= EZBake::Config[:project] %>"
	install -d -m 0755 "$(DESTDIR)$(confdir)/<%= EZBake::Config[:project] %>"
<% EZBake::Config[:config_files].each do |config_file| -%>
	install -m 0644 <%= config_file %> "$(DESTDIR)$(confdir)"
<% end -%>
	install -d -m 0755 "$(DESTDIR)$(defaultsdir)"
	install -m 0644 ext/default "$(DESTDIR)$(defaultsdir)/<%= EZBake::Config[:project] %>"
	install -d -m 0755 "$(DESTDIR)$(initdir)"
	install -m 0755 $(initsrc) "$(DESTDIR)$(initdir)/<%= EZBake::Config[:project] %>"
	install -d -m 0755 "$(DESTDIR)$(rundir)"

#install-terminus:
#    install -d -m 0755 "$(DESTDIR)$(rubylibdir)/puppet/indirector/node"
#    install -m 0644 puppet/lib/puppet/indirector/node/<%= EZBake::Config[:project] %>.rb "$(DESTDIR)$(rubylibdir)/puppet/indirector/node/<%= EZBake::Config[:project] %>.rb"
