prefix = /usr/local
datadir = $(prefix)/share
confdir = /etc
rubylibdir = $(shell ruby -rrbconfig -e "puts RbConfig::CONFIG['sitelibdir']")
rundir = /var/run

<%= EZBake::Config[:uberjar_name] %>:
	lein uberjar
	mv target/<%= EZBake::Config[:uberjar_name] %> <%= EZBake::Config[:uberjar_name] %>

install-<%= EZBake::Config[:project] %>: <%= EZBake::Config[:uberjar_name] %>
	install -d -m 0755 "$(DESTDIR)$(datadir)/<%= EZBake::Config[:real_name] %>"
	install -m 0644 <%= EZBake::Config[:uberjar_name] %> "$(DESTDIR)$(datadir)/<%= EZBake::Config[:real_name] %>"
	install -m 0644 ext/ezbake.manifest "$(DESTDIR)$(datadir)/<%= EZBake::Config[:real_name] %>"
	install -d -m 0755 "$(DESTDIR)$(confdir)/<%= EZBake::Config[:real_name] %>/conf.d"
<% EZBake::Config[:config_files].each do |config_file| -%>
	install -m 0644 <%= config_file %> "$(DESTDIR)$(confdir)/<%= EZBake::Config[:real_name] %>/<%= config_file.sub(/^ext\/config\//, "") %>"
<% end -%>
	install -d -m 0755 "$(DESTDIR)$(rundir)"

<% unless EZBake::Config[:terminus_info].empty? %>
install-<%= EZBake::Config[:project] %>-termini:
<% EZBake::Config[:terminus_info].each do |proj_name, info| -%>
<% info[:files].each do |file| -%>
	install -Dm 0644 <%= file -%> "$(DESTDIR)$(rubylibdir)/<%= file -%>"
<% end -%>
<% end -%>
<% end -%>

install-rpm-sysv-init: install-rpm-preinst
	install -d -m 0755 "$(DESTDIR)$(initdir)"
	install -m 0755 ext/redhat/init "$(DESTDIR)$(initdir)/<%= EZBake::Config[:project] %>"
	install -d -m 0755 "$(DESTDIR)$(defaultsdir)"
	install -m 0644 ext/default "$(DESTDIR)$(defaultsdir)/<%= EZBake::Config[:project] %>"
	install -d -m 0755 "$(DESTDIR)$(rundir)"

install-rpm-systemd: install-rpm-preinst
	install -d -m 0755 "$(DESTDIR)$(defaultsdir)"
	install -m 0644 ext/default "$(DESTDIR)$(defaultsdir)/<%= EZBake::Config[:project] %>"
	install -d -m 0755 "$(DESTDIR)$(unitdir)"
	install -m 0755 ext/<%= EZBake::Config[:project] %>.service "$(DESTDIR)$(unitdir)/<%= EZBake::Config[:project] %>.service"

install-rpm-preinst:
<% EZBake::Config[:redhat][:additional_preinst].each do |preinst| -%>
	<%= preinst %>
<% end -%>

install-deb-sysv-init: install-deb-preinst
	install -d -m 0755 "$(DESTDIR)$(initdir)"
	install -m 0755 ext/debian/<%= EZBake::Config[:real_name] %>.init "$(DESTDIR)$(initdir)/<%= EZBake::Config[:real_name] %>"
	install -d -m 0755 "$(DESTDIR)$(defaultsdir)"
	install -m 0644 ext/default "$(DESTDIR)$(defaultsdir)/<%= EZBake::Config[:project] %>"
	install -d -m 0755 "$(DESTDIR)$(rundir)"

install-deb-preinst:
<% EZBake::Config[:debian][:additional_preinst].each do |preinst| -%>
	<%= preinst %>
<% end -%>

