#!/bin/sh

if [ "$1" = install ] || [ "$1" = upgrade ]; then
 # Create the "classifier" user
    if ! getent passwd classifier  > /dev/null; then
        adduser --quiet --system --group --home /usr/share/classifier  \
            --no-create-home                                 \
            --gecos "Puppet Labs version-checking backend daemon" \
            classifier
    fi

    # Create the "classifier" group, if it is missing, and set the
    # primary group of the "classifier" user to this group.
    if ! getent group classifier > /dev/null; then
         addgroup --quiet --system classifier
         usermod -g classifier classifier
    fi
fi
